# https://stackoverflow.com/questions/27644586/how-to-set-up-travis-ci-with-multiple-languages
matrix:
  include:
    - language: python
      sudo: false
      python:
        - 2.7
        - 3.6
      install:
        - pip install docopt
        - pip install future
        - pip install psutil
      script:
        - python adb-enhanced/setup.py install

    # Source: https://medium.com/@harmittaa/travis-ci-android-example-357f6e632fc4
    # Source: https://stackoverflow.com/a/28751112/434196
    - language: android
      sudo: required  # For pip installation, otherwise, pip install fails.
      jdk: oraclejdk8
      before_cache:
        - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
        - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
      # https://docs.travis-ci.com/user/languages/android/#caching
      cache:
        directories:
          - $HOME/.gradle/caches/
          - $HOME/.gradle/wrapper/
      env:
        global:
          - DX_HEAP_SIZE=2048
          # 16 is the fastest as per
          # https://medium.com/zendesk-engineering/speeding-up-android-builds-on-travis-ci-1bb4cdbd9c62
          - ANDROID_API_LEVEL=16
          - ANDROID_BUILD_TOOLS_VERSION=26.0.1
          - ANDROID_EMU_API_LEVEL=22
          - ANDROID_ABI=armeabi-v7a
          - QEMU_AUDIO_DRV=none  # Remove audio
          - ADB_INSTALL_TIMEOUT=20  # minutes (2 minutes by default)
      android:
        components:
          - tools
          - platform-tools
          - build-tools-$ANDROID_BUILD_TOOLS_VERSION
          - android-$ANDROID_API_LEVEL
          - android-$ANDROID_EMU_API_LEVEL
          # Specify at least one system image
          - sys-img-$ANDROID_ABI-google_apis-$ANDROID_EMU_API_LEVEL
      before_script:
        # Python setup
        - sudo python -m pip install docopt
        - sudo python -m pip install future
        - sudo python -m pip install psutil

        # Android setup
        - echo no | android create avd --force -n test -t android-$ANDROID_EMU_API_LEVEL --abi google_apis/$ANDROID_ABI
        - emulator -avd test -no-window &
        - android-wait-for-emulator
      script:
        - python adbe.py app-signature com.android.phone
        - python adbe.py app-info com.android.phone
      # Default installation is python 2. Let's force python3 and test the code against it.
      # Source: https://github.com/crate/crate/blob/0.56/.travis.yml
      addons:
        apt:
          sources:
            - deadsnakes
          packages:
            # Highest available version whitelisted at
            # https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise
            - python3.5
